### PR TITLE
Feature/get feed posts

### PR DESCRIPTION
**Pull request by keducoop**
Comments:

* Implemented "get_feed_posts()" to get an arbitrary number of posts from personal feed, excluded the promotional ones, sorted by recent (the newest is the first in the list)
* The function will return the post URL in case of a reshared post, and 'IMAGE' in case that the post just contains an image, without text
* Some tests has been provided, taking already existing ones as an example
* The code has been uploaded to git after executing "black .", which leads to changes in some files not modified by this pull request. The reason is to avoid failing of automated pipeline. If that's not the way of proceed don't hesitate on provide guidance.
* This pull request includes an important enhancement compared to our previous one. Is the fact that the posts are reliably returned following the sort order by 'Recent'. To do this we rely on `res.json().get("data", {}).get("*elements", [])`, more details in the code as a comment

### CODE REVIEW

**Comment by tomquirk** [comment]
Awesome stuff here as usual @keducoop . I will look into this one in the coming days (maybe even on the livestream tomorrow  https://www.youtube.com/watch?v=YSxU3N2hsb8)

**Comment by keducoop** [comment]
@tomquirk I found a bug.

I will fix it and submit a new pull request.

**Comment by keducoop** [comment]
@tomquirk ready to go, branch updated, and added an additional [test](https://github.com/Kedu-SCCL/linkedin-api/blob/feature/get_feed_posts/tests/test_linkedin_api_requests.py#L268-L270) to catch this bug in a future.

**Comment by tomquirk** [comment]
Hey @keducoop this looks really great, I'm happy to merge. Could you please fix the conflicts first?

**Comment by keducoop** [comment]
@tomquirk done

**Comment by keducoop** [comment]
@tomquirk anything else that needs to be done before it can be merged?

Thanks

**Comment by jlegido** [comment]
@tomquirk friendly reminder.

**Pull request merged**
