### PR TITLE
Fix linkedin connection request

### PR DESCRIPTION
**Pull request by Zuttam**
- Linkedin has changed the voyager endpoint for adding a connection. Adjusting api to support new endpoint

### CODE REVIEW

**Comment by TheRealVincentVanGogh** [comment]
missing the connection request `customMessage` parameter in the payload:

```
{
  "invitee": {
    "inviteeUnion": {
      "memberProfile": profile_urn
    }
  },
  "customMessage": message
}
```

**Comment by TheRealVincentVanGogh** [comment]
and also it seems like the expected response code is 200 instead of 201 now.

**Comment by BirT356** [comment]
I think using this endpoint also invalidates the session quite quickly, it seems no longer stable as the one before.

**Review by tomquirk — COMMENTED** [review]
Hi @Zuttam thanks for your contribution here. I think we'll proceed with https://github.com/tomquirk/linkedin-api/pull/453 for now because it contains only the code required for the fix.

**Pull request closed without merging**
