### PR TITLE
Added option to get multiple degree connection

### PR DESCRIPTION
**Pull request by bghanchi**
**1 Change Description** 
- Added option to get multiple degree connection based on network_depth.  
- Valid network_depth value is (F,S,T).
- First Degree (F), Second Degree(S), Third Degree (T).
- By default network_depth value is "F".

- Added feature to send bulk message to first, second and third degree connection.
- If first degree connection then direct send message.
- If second or third degree connection then send message with add connection request.

**2.  Testing Details:-**
- Tested end to end by fetching first, second and third degree connection. 
- Test send bulk message with first, second and third degree connection and with various test cases.

### CODE REVIEW

**Comment by abinpaul1** [comment]
Thanks a lot for the PR. Sorry for the delayed reply.
- The option to get multiple degree connections is a good idea. It seems good to merge.
- The second feature `send_bulk_message` seems to be more of a use case of the APIs that are already available rather than a new API. Your function provides a good example of how to use the various APIs linkedin-api provides. 
I think it would be better to maybe move it as an example into the wiki page. What do you say?

To get the build to pass, please do a `black --check .` to correct the formatting.

**Comment by bghanchi** [comment]
Sure, I will do that. Thanks!

**Comment by bghanchi** [comment]
Can we marge send_bulk_message as well. As I know I am using various APIs LinkedIn-API provides. But this can be very helpful who want to send messages in bulk but don't have much coding knowledge. Linkedin is not only used by a software engineer. There lot of people who don't know to code but they also want to send messages in bulk for jobs. So for those this feature can helpful.

**Comment by bghanchi** [comment]
Yeah make sense, Also can you please tell me which wiki you are talking about where I need to add this??. Are you talking about this one https://linkedin-api.readthedocs.io/en/latest/ ??

**Comment by abinpaul1** [comment]
You can add it here by creating a page.(https://github.com/tomquirk/linkedin-api/wiki). You'll be adding our first wiki page 🥳.
Please also update the PR with only the first commit adding the option to get multiple degree connection. Try running a `black --check .` before commiting to fix the formatting issues to get the build to pass. Thank you

**Pull request closed without merging**
