### PR TITLE
Added jobtitle, location and name to search_people

### PR DESCRIPTION
**Pull request by tbressers**
With this change, all available information fields for search_people have become available to the API

### CODE REVIEW

**Comment by tbressers** [comment]
- No documents to update as it only concerns the addition in a result (not documented)
- checks: black is updated (see below)
- pytest returned error (see below) but that can not be related to my change (maybe because I run on Windows?)






(Tensorflow)C:\Users\thijs.bressers\OneDrive - Thermo Fisher Scientific\Documents\Python Scripts\linkedin-api>black --check .
would reformat C:\Users\thijs.bressers\OneDrive - Thermo Fisher Scientific\Documents\Python Scripts\linkedin-api\linkedin_api\linkedin.py
Oh no! 💥 💔 💥
1 file would be reformatted, 13 files would be left unchanged.

(Tensorflow)C:\Users\thijs.bressers\OneDrive - Thermo Fisher Scientific\Documents\Python Scripts\linkedin-api>black .        
reformatted C:\Users\thijs.bressers\OneDrive - Thermo Fisher Scientific\Documents\Python Scripts\linkedin-api\linkedin_api\linkedin.py
All done! ✨ 🍰 ✨
1 file reformatted, 13 files left unchanged.

(Tensorflow)C:\Users\thijs.bressers\OneDrive - Thermo Fisher Scientific\Documents\Python Scripts\linkedin-api>python -m pytest tests -s
========================================================================================= test session starts =========================================================================================
platform win32 -- Python 3.6.12, pytest-4.6.4, py-1.7.0, pluggy-0.12.0
rootdir: C:\Users\thijs.bressers\OneDrive - Thermo Fisher Scientific\Documents\Python Scripts\linkedin-api
collecting 4 items                                                                                                                                                                                     Test config incomplete. Exiting...
Test config incomplete. Exiting...
collected 5 items / 2 errors / 3 selected

=============================================================================================== ERRORS ================================================================================================
________________________________________________________________________ ERROR collecting tests/test_linkedin_api_requests.py _________________________________________________________________________ 
tests\test_linkedin_api_requests.py:21: in <module>
    sys.exit()
E   SystemExit
___________________________________________________________________________ ERROR collecting tests/test_linkedin_client.py ____________________________________________________________________________ 
tests\test_linkedin_client.py:12: in <module>
    sys.exit()
E   SystemExit
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
======================================================================================= 2 error in 2.24 seconds =======================================================================================

**Comment by abinpaul1** [comment]
Hi @tbressers, Thanks a lot for the PR. Unfortunately, the CI is currently in a broken state. I'm a bit strapped for time, so couldn't get around to fixing it up 😞. Your changes seem good. I'll merge once I find a bit of time to fix the CI.

**Comment by tbressers** [comment]
Hi abinpaul1,

Thank you! 

I'd be okay with merging without CI updates... that way I can continue my efforts using the updates...

Best regards - Thijs

**Comment by abinpaul1** [comment]
Thanks again for your fix and patience :) . Really sorry about keeping the PR on hold.

**Pull request merged**
