### PR TITLE
`search_people` using the `Keywords` filter

### PR DESCRIPTION
**Pull request by crouinicrouina**
Hi, small PR here :

1. I added the possibility to search people using the Keywords filters from LinkedIn which are super helpful (see screenshot below)

Screenshot from 2020-06-23 14-42-53

2. I fixed what I think was an issue where `limit` could be `None` which would result in a `TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'` error (please review this change to make sure I didn't break the previous logic even though I don't think so)

### CODE REVIEW

**Comment by crouinicrouina** [comment]
There's now a duplicated parameter : `title` and `keyword_title`. I thought that having the `keyword_` syntax made sense. However, the duplicated params could lead to confusion. We can either : 

- remove the extra `keyword_title` parameter
- remove the `title` parameter (would be a breaking change for some users though)
- let both and then maybe do somethin like `title = title if title else keyowrd_title`

**Comment by tomquirk** [comment]
@crouinicrouina this is fantastic, thank you for the contribution 🥳 . I'm happy to merge this.

Regarding the `title`/`keyword_title` issue, I agree `keyword_title` makes sense, but due to the breaking nature of the change, I would prefer if we did the 3rd option.

I also think a comment next to to the parameters clearly stating that they do the same thing would be helpful as well.

Ping me when you're ready for merge!

**Comment by crouinicrouina** [comment]
As you suggested, I went with the 3rd option and clarified the parameters usage directly in the code (since these parameters are not documented yet in `DOCS.md`.

I think this is ready for merge now :) 

I have a question regarding PR best practices in git (I'm new to git collaboration). Which is better : 

-  Create a PR for separate issues (i.e: 1 to 1 mapping)
- Create a PR for multiple issues at once. For instance, after making this PR, I bumped into a bug : https://github.com/tomquirk/linkedin-api/issues/98 and I'm not sure if I should rather fix this bug in this PR or create a new branch in my forked repository and then create a second PR for this issue (especially since I created this PR prior to finding the bug) ?

**Comment by tomquirk** [comment]
@crouinicrouina awesome! Thank you for adding those comments; super helpful. I am happy to merge this! 🎉 

Regarding your question: in my opinion it's almost always better to opt for creating PR for separate issues, because smaller PRs:

- are easier to review
- can be reverted easier
- are less risky because many things aren't being changed at once
- can be easily referred back to in the future, if someone is seeking additional context for an issue

Again, I really appreciate your contribution here and your comments in some of the issues. Glad to have you involved in the project!

**Pull request merged**
