### PR TITLE
Added easyApply filter to search_jobs()

### PR DESCRIPTION
**Pull request by mwargan**

### CODE REVIEW

**Comment by mwargan** [comment]
@tomquirk is there anything missing that's required to merge?

**Comment by Njoselson** [comment]
@mwargan PR #336 is merged if you want to redo this feature with the new API structure. Otherwise @tomquirk We could add this as a label Good First Issue?

**Comment by mwargan** [comment]
@Njoselson uhh, if I have a bit of time I'll try to update it with the new stuff. What's actually changed that I need to be aware of?

**Comment by tomquirk** [comment]
Going to close this one for now - let's investigate the latest search jobs API stuff separately.

**Pull request closed without merging**
