### PR TITLE
Added add_connection functionality

### LINKED ISSUE #10: Support ability to send Linkedin connection requests
I.e. Add people on Linkedin

POST
```
{"trackingId":"XVpxyROJQ1ybTCQtEFrl8A==","invitations":[],"excludeInvitations":[],"invitee":{"com.linkedin.voyager.growth.invitation.InviteeProfile":{"profileId":"<profile_id>"}}}
```

to url
```
/voyager/api/growth/normInvitations
```

### PR DESCRIPTION
**Pull request by abinpaul1**
Fixes #10, #133 
- Added a function to generate a random TrackingId
- Added add_connection functionality

Do let me know how I could fix the tests as well.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
Please, proceed with this.

**Comment by gazer99** [comment]
@tomquirk Hi Tom, please add this functionality

**Comment by ACC1100** [comment]
Support adding this, have been using functionality without issue.

**Comment by tomquirk** [comment]
Done

**Comment by PMLS3** [comment]
I am getting the following error for 'add_connection': AttributeError: 'Linkedin' object has no attribute 'add_connection'

**Comment by abinpaul1** [comment]
> I am getting the following error for 'add_connection': AttributeError: 'Linkedin' object has no attribute 'add_connection'

Hi, could you post the code you tried running as well.

**Comment by PMLS3** [comment]
> > I am getting the following error for 'add_connection': AttributeError: 'Linkedin' object has no attribute 'add_connection'
> 
> Hi, could you post the code you tried running as well.

Sure its just a test, thanks
Screenshot_3

**Comment by abinpaul1** [comment]
> > > I am getting the following error for 'add_connection': AttributeError: 'Linkedin' object has no attribute 'add_connection'
> > 
> > 
> > Hi, could you post the code you tried running as well.
> 
> Sure its just a test, thanks
> Screenshot_3


I was unable to replicate the error. Could you please check again if you branch is upto date with master.

**Comment by PMLS3** [comment]
> > > > I am getting the following error for 'add_connection': AttributeError: 'Linkedin' object has no attribute 'add_connection'
> > > 
> > > 
> > > Hi, could you post the code you tried running as well.
> > 
> > 
> > Sure its just a test, thanks
> > Screenshot_3
> 
> I was unable to replicate the error. Could you please check again if you branch is upto date with master.

Installed again but same error...

**Comment by abinpaul1** [comment]
> > > > > I am getting the following error for 'add_connection': AttributeError: 'Linkedin' object has no attribute 'add_connection'
> > > > 
> > > > 
> > > > Hi, could you post the code you tried running as well.
> > > 
> > > 
> > > Sure its just a test, thanks
> > > Screenshot_3
> > 
> > 
> > I was unable to replicate the error. Could you please check again if you branch is upto date with master.
> 
> Installed again but same error...

I am not sure then, because the error is because the linkedin object does not have the method defined.
Also maybe from the main folder try running `cat linkedin_api/linkedin.py | grep add_connection`. This should give output as `def add_connection(self, profile_public_id, message="", profile_urn=None):` if the method is defined in the code.

**Comment by tomquirk** [comment]
We haven't done a PyPI release yet, so if you want to use this, make sure you're installing directly from the GitHub repo.

`pip install git+<$GIT_URL>`

**Comment by PMLS3** [comment]
> We haven't done a PyPI release yet, so if you want to use this, make sure you're installing directly from the GitHub repo.
> 
> `pip install git+<$GIT_URL>`

thanks, do I install it from the main branch? Because still got the error after the install. Appreciate your assistance

**Comment by amirsohail12570** [comment]
I'm getting response code 400. Even though connections are sending from browser but not from add_connection method.
Here's the code.
image

**Comment by abinpaul1** [comment]
> I'm getting response code 400. Even though connections are sending from browser but not from add_connection method.
> Here's the code.
> image

Can you try escaping the `\` character. Modify the message string to 
```python
message = 'Hi\\nI would like to add you. \\nCheers'
```

**Comment by amirsohail12570** [comment]
It worked. Thanks!

**Comment by jesusmariajurado** [comment]
Hi @abinpaul1, same problem as @amirsohail12570 here regarding the content of the message. In order to handle special characters, accented characters in Spanish for example, the payload could be encode('utf-8') in the _post call. 

Best regards.

**Pull request merged**
